External automation

diff --git a/.github/workflows/check_game.yml b/.github/workflows/check_game.yml
--- a/.github/workflows/check_game.yml
+++ b/.github/workflows/check_game.yml
@@ -1,7 +1,7 @@
 name: Game Status Check
 on:
-  schedule:
-    - cron: '*/10 * * * *'
+  repository_dispatch:
+    types: [trigger-monitor]
   workflow_dispatch:
 
 jobs:
@@ -27,3 +27,12 @@ jobs:
         env:
           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
         run: python monitor.py
+
+      - name: Commit and Push changes
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git add last_status.txt
+          # The "|| exit 0" prevents the workflow from failing if there are no changes to commit
+          git commit -m "chore: update game status [skip ci]" || exit 0
+          git push
